アーカイブ関連の修正
minarin0179/Madaminalink_v2 pull request #25
Opened 2023-12-15 15:27 UTC by minarin0179

- リアクションが保存内容に含まれるように変更しました
- 保存時にuseridのほうを参照していたのでユーザーの表示名を参照するように変更しました
- コードのリファクタリグを行いました

2023-12-18 15:06 UTC, yuki-murder requested changes
1. とりあえず、最後の「no new line at end of file」が気になります

2. botがいるサーバーにあるオリジナル絵文字がID？だけになって化けるのは回避不能ですか？

3. botがいないサーバーにあるオリジナル絵文字がIDすら出ないのは回避不能ですか？

とりあえず、1は修正かなあって思うのでrequest changesにしてます。
2と3は無理な可能性もあるのでどちらでも。

2024-01-06 07:16 UTC, yuki-murder reviewed
大変遅くなりました。
概ね非常にいいと思います！
1. Discordで鯖外絵文字の扱いについて提案を投げています。ご確認をお願いします。
2. またno new lineしてるので、ついでがあれば直していただけると……

2024-01-07 15:05 UTC, minarin0179 commented
1. 相談しつつ仕様きめましょう
2. 申し訳ないです… 1.が決まったら同じタイミングで修正入れます

2024-01-29 06:19 UTC, minarin0179 commented
No new line は修正しました
鯖外絵文字については一旦表示しないという方針で進めようと思います
その他特に問題なければApprove&Mergeまでお願いします

2024-02-09 00:29 UTC, minarin0179 commented
@yuki-murder

2024-02-17 02:35 UTC, yuki-murder approved these changes

2024-02-17 02:36 UTC, merged

2024-02-17 02:36 UTC, yuki-murder commented
大変お待たせいたしました。LGTMです。